# Generated by Django 4.2.5 on 2023-12-07 22:25

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sala', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChaveSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código da chave da Sala', max_length=10, unique=True, verbose_name='Código')),
                ('disponibilidade', models.CharField(choices=[('S', 'sim'), ('N', 'não')], default='S', help_text='Disponibilidade da chave', max_length=1, verbose_name='Disponibilidade')),
                ('sala', models.ForeignKey(help_text='Sala da chave', on_delete=django.db.models.deletion.PROTECT, related_name='sala_chave', to='sala.sala', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Chave da Sala',
                'verbose_name_plural': 'Chaves das Salas',
                'ordering': [django.db.models.functions.text.Upper('sala')],
            },
        ),
    ]
