# Generated by Django 4.2.5 on 2025-05-19 17:08

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('chavesala', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chavesala',
            options={'ordering': [django.db.models.functions.text.Upper('sala__numero')], 'verbose_name': 'Chave da Sala', 'verbose_name_plural': 'Chaves das Salas'},
        ),
    ]
