# Generated by Django 4.2.5 on 2023-12-07 22:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chavebloco', '0001_initial'),
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetiradaBlocoP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, help_text='Data de retirada', verbose_name='Data')),
                ('devolucao', models.DateTimeField(default=django.utils.timezone.now, help_text='Data de devolução', verbose_name='Devolução')),
                ('status', models.CharField(default='Retirada', help_text='Status da Retirada', max_length=9, verbose_name='Status')),
                ('chave', models.ForeignKey(help_text='Chave retirada', limit_choices_to={'disponibilidade': 'S'}, on_delete=django.db.models.deletion.PROTECT, related_name='retirada_chaveblocop', to='chavebloco.chavebloco', verbose_name='Chave Bloco')),
                ('professor', models.ForeignKey(help_text='Professor Retirante', on_delete=django.db.models.deletion.PROTECT, related_name='professor_bloco', to='professor.professor', verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Retirada de BlocoP',
                'verbose_name_plural': 'Retiradas de BlocosP',
                'ordering': ['-devolucao'],
            },
        ),
    ]
