# Generated by Django 4.2.5 on 2023-12-07 22:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionario', '0001_initial'),
        ('chavesala', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetiradaSalaFunc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, help_text='Data de retirada', verbose_name='Data')),
                ('devolucao', models.DateTimeField(default=django.utils.timezone.now, help_text='Data de devolução', verbose_name='Devolução')),
                ('status', models.CharField(default='Retirada', help_text='Status da Retirada', max_length=9, verbose_name='Status')),
                ('chave', models.ForeignKey(help_text='Chave retirada', limit_choices_to={'disponibilidade': 'S'}, on_delete=django.db.models.deletion.PROTECT, related_name='retirada_chavesala', to='chavesala.chavesala', verbose_name='Chave Sala')),
                ('funcionario', models.ForeignKey(help_text='Funcionario Retirante', on_delete=django.db.models.deletion.PROTECT, related_name='funcionario_sala', to='funcionario.funcionario', verbose_name='Funcionario')),
            ],
            options={
                'verbose_name': 'Retirada de Sala',
                'verbose_name_plural': 'Retiradas de Salas',
                'ordering': ['-devolucao'],
            },
        ),
    ]
