# Generated by Django 4.2.5 on 2023-12-07 22:25

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo', max_length=50, verbose_name='Nome')),
                ('fone', models.CharField(help_text='Número de telefone - ex: (00)12345-6789', max_length=14, unique=True, verbose_name='Telefone')),
                ('email', models.EmailField(help_text='Endereço de E-mail', max_length=100, unique=True, verbose_name='E-mail')),
                ('matricula', models.CharField(help_text='Matricula UFSM', max_length=12, verbose_name='Matricula')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': [django.db.models.functions.text.Upper('nome')],
            },
        ),
    ]
