# Generated by Django 4.2.5 on 2023-12-07 22:25

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bloco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChaveBloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código da chave do bloco', max_length=10, unique=True, verbose_name='Código')),
                ('disponibilidade', models.CharField(choices=[('S', 'sim'), ('N', 'não')], default='S', help_text='Disponibilidade da chave', max_length=1, verbose_name='Disponibilidade')),
                ('bloco', models.ForeignKey(help_text='Bloco da chave', on_delete=django.db.models.deletion.PROTECT, related_name='bloco', to='bloco.bloco', verbose_name='Bloco')),
            ],
            options={
                'verbose_name': 'Chave do Bloco',
                'verbose_name_plural': 'Chaves do Bloco',
                'ordering': [django.db.models.functions.text.Upper('bloco')],
            },
        ),
    ]
