# Generated by Django 4.2.5 on 2025-05-19 17:08

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('chavebloco', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chavebloco',
            options={'ordering': [django.db.models.functions.text.Upper('bloco__nome')], 'verbose_name': 'Chave do Bloco', 'verbose_name_plural': 'Chaves do Bloco'},
        ),
    ]
